### ISSUE TITLE
Read error on bad image

### ISSUE THREAD

**Issue by Stiropor** [InfinetyEs/Nova-Filemanager#120]
If there is a problem with image (we had a problem with some images on server being zero files big) and filemanager returning error. When inspecting log there was `getimagesize(): Read error!`. Is there any way to skip/ignore such messages?

**Comment by underwear** [comment]
same problem

**Comment by underwear** [comment]
I use s3 storage as public disk and got this problem. I think that is because of method `\Infinety\Filemanager\Http\Services\GetFiles::getImageDimesions` has condition on public storage. I copied public disk config in `filesystems` and called it 's3'. Also i added FILEMANAGER_DISK=s3 and it worked for me.

**Comment by Krato** [comment]
Please try v2.8 Should be ok.
